name: auto build engine

on: 
  release:
    types: [published]
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: 
      - master
  watch:
    types: [started]

defaults:
  run:
    working-directory: /root
       
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    #- name: Maximize build space
    #  uses: easimon/maximize-build-space@master
    #  with:
    #    root-reserve-mb: 4096

    - name: Bulid Armbian
      run: |
        sudo git clone https://github.com/armbian/build --depth 1
        sudo cd build
        sudo ./compile.sh BOARD="rockpi-4b" BRANCH=current RELEASE=bullseye KERNEL_ONLY=no KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=no 
        
    - name: Upload Armbian
      uses: actions/upload-artifact@master
      with:
        name: image
        path: build/output/image/*.img

