name: auto build engine

on: 
  release:
    types: [published]
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: 
      - master
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    #- name: Maximize build space
    #  uses: easimon/maximize-build-space@master
    #  with:
    #    root-reserve-mb: 4096

    - name: Bulid Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1
        cd build
        ./compile.sh  BOARD=rockpi-4b BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img
        
    - name: Upload Armbian
      uses: actions/upload-artifact@master
      with:
        name: image
        path: build/output/images/*.img

